services:
  musicdl:
    image: nicoenking/musicdl
    volumes:
      - nodeStorage:/app/storage
    environment:
      - VIRTUAL_HOST=musicdl.de,www.musicdl.de
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=musicdl.de,www.musicdl.de
      - LETSENCRYPT_EMAIL=nico.enking@gmail.com
    networks:
      - nginx

volumes:
  nodeStorage:
    driver: local

networks:
  nginx:
    name: nginx
    external: true
