services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - musicdl
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - musicdl
    environment:
      - DEFAULT_EMAIL=nico.enking@gmail.com
    depends_on:
      - nginx-proxy

  musicdl:
    image: nicoenking/musicdl
    environment:
      - VIRTUAL_HOST=musicdl.de
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=musicdl.de
      - LETSENCRYPT_EMAIL=nico.enking@gmail.com
    networks:
      - musicdl

volumes:
  certs:
    driver: local
  vhost:
    driver: local
  html:
    driver: local
  acme:
    driver: local
  

configs:
  httpd-config:
    external: true

secrets:
  server-certificate:
    external: true

networks:
  # The presence of these objects is sufficient to define them
  musicdl: {}
